config/routes.rb
Faxjax3::Application.routes.draw do |map|
    
    match '/pid/q/s/:id',:to => "pid#show"
    match '/PID/q/s/:id',:to => "pid#show"
    match '/pid', :to => "pid#index"

  map.sitemap '/sitemap.xml', :controller => 'sitemap', :action => 'sitemap'
  
    map.connect '', :controller => "home"
    map.connect '/admin', :controller => "admin/index"

    map.connect '', :controller => "home/how_it_works"
    
    map.connect '', :controller => "listings/image"
     map.connect ':controller/service.wsdl', :action => 'wsdl'

     map.connect '/reset/:id', :controller => 'home', :action => 'reset'

     map.connect ':controller/:action/:id'
    
    
  

end

app/models/pid.rb
class Pid < ActiveRecord::Base
  include Listable
  
  belongs_to :user
end

app/controllers/pid_controller.rb
class PidController < ApplicationController
  
  def index
    if params[:search]
          @pid = Pid.find_by_code(params[:search].to_s)
          @message_controller = 'messages' if @message_controller.nil?
          @message_action = 'new' if @message_action.nil?
          if !@pid.user.present?
             flash[:warning] = "This code is not in use."
          end  
    end  
  end
  
  def send_message
    @pid = Pid.find params[:message][:pid_id].to_i
    
    unless @pid.nil?
      message = Message.create_with_nonce params[:message]
      message.from_user_id = active_user.id if logged_in?
      message.save
      url = "#{request.protocol}#{request.host}" + (request.port.blank? ? '' : ":#{request.port}")
      
      if @pid.mail_user message, url
        flash[:notice] = "Your message has been sent to #{@pid.user.first_name + " " + @pid.user.last_name}!"
        redirect_to :controller => "pid", :action=>"index"
      else
        flash[:warning] = "The email was not sent. Please contact Faxjax, Inc. support."
        redirect_to :controller => "pid", :action=>"index"
      end
    end
  end
  
  def show
    @pid = Pid.find_by_code(params[:id].to_s)
    if @pid.blank?
      flash[:warning] = "Invalid code entered. Please retry you search."
      redirect_to :action => 'index'
    else
      redirect_to("http://www.fastidtag.com/pid/q/s/#{@pid.code}")
    end
   
  end
  
  def activate
    if !logged_in
        redirect_to_login
        session[:activating_pid] = true
        session[:activating_pid_code] = params[:code]
        session[:activating_pid_key1] = params[:key1]
        session[:activating_pid_key2] = params[:key2]
        session[:activating_pid_key3] = params[:key3]
        session[:activating_pid_key4] = params[:key4]
        flash[:info] = "Please <a href=\"#{url_for :controller => 'home', :action => 'sign_in'}\">sign in</a> or <a href=\"#{url_for :controller => 'users', :action => 'new'}\">create an account</a> before activating."
   else
     render 'activate'
       
   end
  
  end
  
  
  def activated
    @pid = Pid.find_by_code(params[:code].to_s)
    
    if @pid.blank?
      flash[:warning] = "Invalid code entered!"
      redirect_to :action => "activate"
    else
        key = params[:key1] + params[:key2] + params[:key3] + params[:key4]
        
        if @pid.key.gsub(/[-\s+]/,"") == key.to_s.gsub(/[-\s+]/,"") 
             @pid.user_id = active_user.id
             @pid.save
             @user = User.find(@pid.user_id)
             @user.update_attributes(:address => params[:address],:address2 => params[:address2],:city => params[:city],:state => params[:user][:state],:zip => params[:zip])
             @user.save(:validate => false)
             flash[:notice] = "Successfully activated the code"
             redirect_to :action => "activate"
             
          else
            flash[:warning] = "The key to activate the code is invalid"
            render "activate" 
        
        end
        
      
    end   
  end  

end

app/helpers/pid_helper.rb
module PidHelper
end

app/views/pid/_message_form.html.erb
<%= form_for @message,:as => :message, :url => {:controller => "pid", :action => "send_message", :id => @message_id} do |f| %>
    <%= f.hidden_field :pid_id, :value=>@pid.id %>
  <div>
    <label>To:</label>
    <%= h("Owner") %>
    <%= f.hidden_field :user_id, :value => @pid.user_id %> 
  </div>
  <div>
  <% if !logged_in? %>
    <label for="message_from_email">Your Email: <%= required_if_empty('').html_safe %></label>
    <%= f.text_field :from_email, :size=>40 , :maxlength=> 40 %>
  <% else %>
    <%= f.hidden_field :from_email, :value => active_user.email %>
  <% end %>
  </div>
  <div>
    <label for="message_subject">Subject:</label>
    <%= f.text_field :subject, :size=>40, :maxlength=> 100 %>
  </div>
  
  <div>
    <label for="message_message">Message:</label>
    <%= f.text_area :message, {:cols=>40, :rows=>5, :onkeyup => "return updateCharactersLeft(event, this, 1000);", :onkeypress => "return updateCharactersLeft(event, this, 1000);"} %><br/>
    Characters left: <strong id="message_message-charsleft">1000</strong>
    <script type="text/javascript">
    <!--
      Event.observe(window, 'load', updateMessageCharactersLeft, false);
      function updateMessageCharactersLeft(event) {
        updateCharactersLeft(event, $('message_message'), 1000);
      }
    //-->
    </script>
  </div>

  <div>
  <%= submit_tag "Send Message", {:class => "submit"} %>
  </div>
  <i> <%= required_if_empty('').html_safe %>Your email address will only be shared with this listing owner.
<% end %>

app/views/pid/activate.html.erb
<br/><div id="activate">
<% form_tag('/pid/activated') do %>
  <%= error_messages_for 'pid' %>
  <fieldset>
  <legend>Enter Your  Code &amp; PIN #</legend>
  <div>[&nbsp;<a style="color:red">*</a>&nbsp; Mandatory Fields&nbsp;]<br/><br/>
  <div>
    <label for="sign_code">1. PID code:</label>
    <%= text_field_tag "code", !session[:activating_pid_code].nil? ? session[:activating_pid_code] : params[:code], { :size => 8, :maxlength => 10, :class => "sign-code" } %>&nbsp;<span class="required">*</span>
  </div>
  <div>
    <label for="activation_key">2. PIN #:</label>
    <%= text_field_tag "key1", !session[:activating_pid_key1].nil? ? session[:activating_pid_key1] : params[:key1], { :size => 3, :maxlength => 4, :onkeyup => "handlePINKeyUp(event, this, 1);"  } %>
    <%= text_field_tag "key2", !session[:activating_pid_key2].nil? ? session[:activating_pid_key2] : params[:key2], { :size => 3, :maxlength => 4, :onkeyup => "handlePINKeyUp(event, this, 2);"  } %>
    <%= text_field_tag "key3", !session[:activating_pid_key3].nil? ? session[:activating_pid_key3] : params[:key3], { :size => 3, :maxlength => 4 } %>
    <%= text_field_tag "key4", !session[:activating_pid_key4].nil? ? session[:activating_pid_key4] : params[:key4], { :size => 3, :maxlength => 4 } %>&nbsp;<span class="required">*</span>	
    <%
      # Clear out the keys in the session
      session[:activating_pid] = nil
      session[:activating_pid_code] = nil
      session[:activating_pid_key1] = nil
      session[:activating_pid_key2] = nil
      session[:activating_pid_key3] = nil
      session[:activating_pid_key4] = nil
    %>
  </div><% if active_user %>
   <div>
    <label for="sign_code">3. Address:</label>
    <%= text_field_tag( :address,active_user.address) %>&nbsp;
  </div>
   <div>
    <label for="sign_code">4. Address2:</label>
    <%= text_field_tag( :address2,active_user.address2) %>&nbsp;
  </div>
  <div>
    <label for="sign_code">5. City:</label>
    <%= text_field_tag( :city,active_user.city) %>&nbsp;
  </div>
  <div>
    <label for="sign_code">6. State:</label>
	<select id="user_state" name="user[state]">
    <option value=""></option>
     	<%= state_abbrev_options_for_select(active_user.state) %>
    </select>&nbsp;
  </div>
  <div>
    <label for="sign_code">7. Zip Code:</label>
    <%= text_field_tag(:zip,active_user.zip) %>&nbsp;
  </div> 
  <%= submit_tag "Activate", {:class => "submit"} %>
  <% else %>	
  <div>
          <p style="color:red;"> You need to be logged in as user to activate the PID</p>
  </div>
  <% end %> 
  </fieldset>
<% end %>
</div>

app/views/pid/index.html.erb
<h1>Welcome to Faxjax Lost and Found Center</h1>
<br/><br/>
<p>FAXJAX produces a line of Fast-Action ID TagsTM that allows people to protect their valuable properties while keeping their identity safe. </p>  
<br/><br/> 
<p>FAXJAX provides a secure method for recovery of personal items such as keys, phones, laptops, cameras, and so much more! </p>
<br/>
<br/>
<p>Save money, reduce anxiety, with this safe, easy way to recover your property.</p>
<br/>
<br/>
<p>Go to faxjax.com/sign_products/list to see our full line of PID Tags.  PID Tags are available in two adhesive sizes, as a key chain, a pet tag and a luggage tag.</p>
<br/>
<%= form_tag pid_path, :method => 'get'  do  %>
<h3>Code:&nbsp;&nbsp;&nbsp;<%= text_field_tag :search %>&nbsp;&nbsp;<%= submit_tag "Search" %></h3>
<% end %>
<br/>
<br/>
<br/>
<% if active_user %>
<h3><%= link_to("Activate",:controller => "pid",:action => "activate")%></h3>
    <% else %>
<h3><%= link_to("Activate",:controller => "home",:action => "sign_in")%></h3>
<% end %>
<br/>
<br/>
<br/>
<% if @pid && @pid.user.present? %>
		
	<% if show_message_form? %>
	<div>
  		<div>
    			<button type="button" class="submit" id="send-message-btn">Send message to Owner</button>
  		</div>
  		<div id="send-message" style="display: none">
    			<h3>Please enter your Message:</h3>
    			<%= render :partial => "message_form" %>
  		</div>
	</div>
	<% end %>  

<% end %>

app/views/pid/show.html.erb
<% if @pid && @pid.user.present? %>
	<% if show_message_form? %>
	<div>
  		<div>
    			<button type="button" class="submit" id="send-message-btn">Send message to Owner</button>
  		</div>
  		<div id="send-message" style="display: none">
    			<h3>Please enter your Message:</h3>
    			<%= render :partial => "message_form" %>
  		</div>
	</div>
	<% end %>  
<% end %>
  
    
  